### ISSUE TITLE
Webpack unable to load binary "sdk-napi.win32-x64-msvc.node" when using "@bitwarden/sdk-napi" in a NextJS 13 App Dir API route ( Edge runtime & Node.js runtimes )

### ISSUE THREAD

**Issue by jules-sommer** [bitwarden/sdk#112] opened 2023-07-17 20:11 UTC
### Steps To Reproduce

- Step 1: Clone a Next JS 13 App Dir project using create-next-app
```npx create-next-app@latest```
- Step 2: Install the SDK and project deps using your package manager of choice, in my case ```pnpm add @bitwarden/sdk-napi```, this should also install the package-lock.json deps.
- Step 3: Create an api route by creating a new api folder in the src/app directory and a subsequent bitwarden folder containing a route.ts file such that our API can be hit at ```http://localhost:3000/api/bitwarden``` with a GET request
- Use the following boilerplate code taken from the SDK docs to instantiate our API route with a GET handler that returns a JSON response of our secrets ( created and saved ahead of time in the Secrets Manager dashboard ).
```ts
import { BitwardenClient, ClientSettings, DeviceType, LogLevel } from "@bitwarden/sdk-napi";
import { NextResponse, type NextRequest } from 'next/server'

// Note this error will occur if you omit this config to run the API route in a NodeJs runtime
export const config = {
    runtime: 'edge',
}

export default async function GET(req: NextRequest) {

    // Optional settings
    const settings: ClientSettings = {
        apiUrl: "https://api.bitwarden.com",
        identityUrl: "https://identity.bitwarden.com",
        userAgent: "Bitwarden SDK",
        deviceType: DeviceType.SDK,
    };

    const accessToken = process.env.BW_ACCESS_TOKEN;

    const client = new BitwardenClient(settings, LogLevel.Info);

    // Authenticating using a service accounts access token
    const result = await client.loginWithAccessToken(accessToken);
        if (!result.success) {
            throw Error("Authentication failed");
    }

    // List secrets
    const secrets = await client.secrets().list();

    return NextResponse.json(secrets, { status: 200 });

}
```
- Step 4: Run the dev server by running ```pnpm run dev``` ( or npm / yarn, etc depending on your local environment )
- Step 5: Open a web browser and navigate to ```http://localhost:3000/api/bitwarden``` thus sending the GET request to the server we've just created to be greeted by the error I am receiving on my local reproduction which pasted below:
```ts
./node_modules/.pnpm/@bitwarden+sdk-napi-win32-x64-msvc@0.2.1/node_modules/@bitwarden/sdk-napi-win32-x64-msvc/sdk-napi.win32-x64-msvc.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
``` 

### Expected Result

So obviously the secrets manager is in beta and I was excited to test it out in a production environment, in this case a NextJs 13 web app, I wanted to created an API route ( which would obviously be behind authentication in production, however is not in this reproduction for brevity ) that would return a JSON serialized list of the secrets in my BW Secrets Manager project.

Curious to hear what you have to say about this, I am aware I might be using the SDK out of its intended environment, though NextJS api routes are NodeJS runtime and I would expect this to work, though obviously my webpack bundler is having some trouble with the SDK module.

Thanks for taking the time, and I appreciate any feedback!

### Actual Result

Again, I am getting this build error when pulling that SDK into my NextJS application.
```ts
./node_modules/.pnpm/@bitwarden+sdk-napi-win32-x64-msvc@0.2.1/node_modules/@bitwarden/sdk-napi-win32-x64-msvc/sdk-napi.win32-x64-msvc.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
``` 

### Screenshots or Videos

![image](https://github.com/bitwarden/sdk/assets/56566563/02b9ac28-6606-4fe7-a714-488c458189f4)

### Operating System

Windows

### Build Version

@bitwarden/sdk-napi-win32-x64-msvc@0.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment] 2023-07-18 14:44
Hi @jules-sommer,

The Napi SDK (Node-API) is only compatible with node.js. By default Webpack attempts to bundle external dependencies, I'm not well versed with how next.js works, but I've previously used `externals` https://webpack.js.org/configuration/externals/ to inform webpack to not bundle it, and instead depend on the `node_modules` version.

https://github.com/vercel/next.js/discussions/17807 suggests using `__non_webpack_require__`.

**Comment by jules-sommer** [comment] 2023-07-18 15:11
> Hi @jules-sommer,
> 
> The Napi SDK (Node-API) is only compatible with node.js. By default Webpack attempts to bundle external dependencies, I'm not well versed with how next.js works, but I've previously used `externals` https://webpack.js.org/configuration/externals/ to inform webpack to not bundle it, and instead depend on the `node_modules` version.
> 
> [vercel/next.js#17807](https://github.com/vercel/next.js/discussions/17807) suggests using `__non_webpack_require__` which also seems to avoid the webpack bundling.

Oh, nice - thank you; that's a fairly clean solution to avoid having webpack bundle it leaving me dependent on the NPM module alone - still will be interesting to see if it runs well in a NextJs API route, but without that bundling I see no reason why it wouldn't run as API routes are NodeJs runtime by default. I will play around with that and get back to you, thanks for the quick response!

**Comment by jules-sommer** [comment] 2023-07-18 17:34
```ts
{
  data: null,
  errorMessage: 'Internal error: Failed to parse IdentityTokenResponse',
  success: false
}
```
I am now getting this error with a valid access token ( triple-checked ) and the error throws at client.loginWithAccessToken funtion. Any thoughts?

**Comment by Hinton** [comment] 2023-07-20 20:38
That typically means the response from the bitwarden server is malformed, it could be due to quite a few reasons. We recently merged a change in https://github.com/bitwarden/sdk/pull/109 that improves the error message for this and it will be included in the next release.

**Comment by Hinton** [comment] 2023-07-27 12:24
@jules-sommer Version 0.3.0 which just got released to npm should provide better error handling for the IdentityTokenResponse error.

**Comment by Hinton** [comment] 2023-07-27 15:07
That definitely sounds like a but on our end. I believe it's caused by our NAPI integration initializing the logger multiple times. I'll break out a new issue for this.

**Comment by jules-sommer** [comment] 2023-07-27 18:23
> That definitely sounds like a bug on our end. I believe it's caused by our NAPI integration initializing the logger multiple times. Could you try creating a single instance of the `BitwardenClient` and persist it between requests?
> 
> I'll break out a new issue for this.

Thanks so much for helping me out with this, I appreciate it - and yes, I suppose the way my code is written currently, a new instance of the client is created every time the API is hit, I hadn't thought of that being an issue. Come to think of it though, I already solve this problem elsewhere in my codebase for the database, I just have a utility function check if an instance has been initialized and if not create one otherwise return the existing so I don't have thousands of open connections to my DB in prod. I will try to apply that same logic to the BW client and see what happens!

**Comment by jules-sommer** [comment] 2023-07-27 20:38
So with a global client instance this is the error I am getting now, it seems to have changed the behaviour slightly in the direction of functionality but I've not quite got it yet.

```
{
  data: null,
  errorMessage: 'Internal error: Failed to parse IdentityTokenResponse',     
  success: false
}
- error Error: Invalid value for key "secrets" on Command. Expected an optional object but got {"list":{}}
```

**Comment by jules-sommer** [comment] 2023-08-01 20:22
> The last error message indicates that the command is missing an argument. `list` expects an organization id to be provided. After modifying your example slightly and providing an org id it seems to work on my machine.
> 
> Can you try updating your code with:
> 
> ```ts
> const secrets = await client.secrets().list("org-id");
> ```

Okay, I didn't catch that in the docs, but for the life of me I can't figure out what organization id you're referring to - again, searching through the docs I only see an OID referenced for SSO, but nothing with regards to this SDK or the secrets manager in general, this is totally just my ignorance in using this SDK and is probably why I can't authenticate; but I've searched around my API keys and such in the BW web vault dashboard, as well as the docs, for about an hour and couldn't find the specific token you're referencing. When I setup the SDK the only .env variable I set was my access token.

I've been working on another project so haven't had a minute to check in here, hence my late reply, so sorry about that as well, and forgive my ignorance and lack of familiarity with your SDK.

Hopefully this is all that's preventing my code from running and I will be sorted once I find this other identifier I am after.

**Comment by jules-sommer** [comment] 2023-08-09 05:52
> We haven't yet properly documented the node api unfortunately.
> 
> The organization id is visible in the url. When going to the secrets manager dashboard you have a url like `https://vault.bitwarden.com/#/sm/00000000-0000-0000-0000-000000000000` the number after `sm` is the organization id.

I would love to help with that if it's open source, given I now have some experience, but thank you, I will try it and update the issue if that finally gets me going with the SDK!!

**Comment by Hinton** [comment] 2023-12-19 11:20
Hey @jules-sommer,

I'm closing this issue since I believe we resolved the root cause of your issues. Hopefully the secret manager team can get some documentation published soon.

**Closed by Hinton** 2023-12-19 11:20 UTC
Labels: bug
